# Generated by Django 4.2.27 on 2025-12-29 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCompany',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('social_type', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='about_company_icons/')),
                ('social_url', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImpactMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_projects', models.IntegerField()),
                ('happy_clients', models.IntegerField()),
                ('industries_served', models.IntegerField()),
                ('success_rate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Journeys',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Year', models.CharField(max_length=4)),
                ('short_Description', models.CharField(max_length=255)),
                ('Description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Offices',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Location', models.CharField(max_length=100)),
                ('Address', models.TextField()),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service_Categories',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='team_members/')),
                ('Name', models.CharField(max_length=100)),
                ('Role', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('SocialLink', models.URLField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Technologies',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='technologies/')),
                ('technology', models.CharField(max_length=100)),
                ('technology_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WhayChooseUs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='why_choose_us_icons/')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='projects/')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('Link', models.URLField(max_length=300)),
                ('Technologies', models.ManyToManyField(related_name='projects', to='apps.technologies')),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioProjects',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='portfolio_projects/')),
                ('Title', models.CharField(max_length=200)),
                ('Link', models.URLField(max_length=300)),
                ('Client', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.service_categories')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=100)),
                ('Company', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.service_categories')),
            ],
        ),
        migrations.CreateModel(
            name='LeadershipTeamMembers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.teammembers')),
            ],
        ),
    ]
