# Generated by Django 4.2.27 on 2025-12-29 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WhayChooseUs',
            new_name='WhyChooseUs',
        ),
    ]
