# Generated by Django 4.2.27 on 2025-12-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_rename_whaychooseus_whychooseus'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='service_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.service_categories'),
        ),
    ]
