# Generated by Django 4.2.27 on 2025-12-29 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_projects_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service_categories',
            name='Service_Options',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_categories',
            name='Title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service_categories',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='service_categories',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='service_category_icons/'),
        ),
        migrations.AlterField(
            model_name='service_categories',
            name='category_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
