# Generated by Django 4.2.27 on 2025-12-30 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_service_categories_service_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartneredIndustiries',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('industry_name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='partnered_industries_icons/')),
                ('MediaLink', models.URLField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressionMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('platform', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='social_media_icons/')),
                ('url', models.URLField(max_length=300)),
            ],
        ),
    ]
