# Generated by Django 4.2.27 on 2025-12-30 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_partneredindustiries_progressionmetrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressionmetrics',
            name='description',
            field=models.TextField(),
        ),
    ]
