# Generated by Django 4.2.27 on 2025-12-30 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_alter_progressionmetrics_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Owner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
